### ISSUE TITLE
Schemasync TypeError 

### ISSUE THREAD

**Issue by eileenzliu** [mmatuson/SchemaSync#29]
I got the following errors when trying to run schemasync on two databases:

Traceback (most recent call last):
  File "/usr/local/bin/schemasync", line 9, in <module>
    load_entry_point('SchemaSync==0.9.2', 'console_scripts', 'schemasync')()
  File "build/bdist.macosx-10.9-intel/egg/schemasync/schemasync.py", line 264, in main
  File "build/bdist.macosx-10.9-intel/egg/schemasync/schemasync.py", line 123, in processor
  File "build/bdist.macosx-10.9-intel/egg/schemasync/schemasync.py", line 210, in app
  File "build/bdist.macosx-10.9-intel/egg/schemaobject/schema.py", line 48, in selected
  File "build/bdist.macosx-10.9-intel/egg/schemaobject/schema.py", line 67, in databases
  File "build/bdist.macosx-10.9-intel/egg/schemaobject/database.py", line 29, in DatabaseSchemaBuilder
  File "build/bdist.macosx-10.9-intel/egg/schemaobject/connection.py", line 63, in execute
  File "/Library/Python/2.7/site-packages/MySQL_python-1.2.4-py2.7-macosx-10.9-intel.egg/MySQLdb/cursors.py", line 187, in execute
    query = query % tuple([db.literal(item) for item in args])
TypeError: not all arguments converted during string formatting

After I installed the schema sync, I had to run the following command to get rid of an error complaining "Mysqldb" not found.

sudo ln -s /usr/local/mysql/lib/libmysqlclient.18.dylib /usr/lib/libmysqlclient.18.dylib

Any clue what the problem is?

Thanks!

**Comment by afilina** [comment]
The package 1.2.4 is not available. I installed MySQLdb 1.2.3 using this:
```
sudo pip install -Iv http://sourceforge.net/projects/mysql-python/files/mysql-python/1.2.3/MySQL-python-1.2.3.tar.gz/download
```

My schemasync command worked fine after that.
