### ISSUE TITLE
I came across an error

### ISSUE THREAD

**Issue by gitjacky** [mmatuson/SchemaSync#62]
my py version is 2.6   and i installed SchemaSync,but ,when when i run it throw out an error like this below:

Traceback (most recent call last):
  File "/usr/bin/schemasync", line 9, in <module>
    load_entry_point('SchemaSync==0.9.5', 'console_scripts', 'schemasync')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 550, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2710, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2370, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2376, in resolve
  File "/usr/lib/python2.6/site-packages/schemasync/schemasync.py", line 34, in <module>
    import schemaobject
  File "/usr/lib/python2.6/site-packages/schemaobject/__init__.py", line 11, in <module>
    from schemaobject.schema import SchemaObject
  File "/usr/lib/python2.6/site-packages/schemaobject/schema.py", line 1, in <module>
    from schemaobject.connection import DatabaseConnection
  File "/usr/lib/python2.6/site-packages/schemaobject/connection.py", line 1, in <module>
    import pymysql
  File "/usr/lib/python2.6/site-packages/pymysql/__init__.py", line 96, in <module>
    from . import connections as _orig_conn
  File "/usr/lib/python2.6/site-packages/pymysql/connections.py", line 79
    FIELD_TYPE.BIT,
                  ^
SyntaxError: invalid syntax

This is the connections.py:
TEXT_TYPES = {
    FIELD_TYPE.BIT,
    FIELD_TYPE.BLOB,
    FIELD_TYPE.LONG_BLOB,
    FIELD_TYPE.MEDIUM_BLOB,
    FIELD_TYPE.STRING,
    FIELD_TYPE.TINY_BLOB,
    FIELD_TYPE.VAR_STRING,
    FIELD_TYPE.VARCHAR,
    FIELD_TYPE.GEOMETRY,
}

this is not a dict but a list , Is Schemasync dependent on pymysql?

**Comment by mitsh** [comment]
i accept merge request about fixed this issue. please check it again.
